print ("kolme lukua ovat ")
luku1 = float(input("Syötä ensimmäinen luku: "))
luku2 = float(input("Syötä toinen luku: "))
luku3 = float(input("Syötä kolmas luku: "))
summa = float(luku1 + luku2 + luku3)
print("Lukujen summa on: " + str(summa))
tulo = float(luku1 * luku2 * luku3)
print("Lukujen tulo on: " + str(tulo))
keskiarvo = float(summa / 3)
print("Lukujen keskiarvo on: " + str(keskiarvo))    
